Add nginx tests for two nodes testing
TODO:
- uncomment tests which are commented out

The reason is:
kubectl exec -it ubuntu-server-6d9ccdbf44-6xcwx -- /bin/bash
error: unable to upgrade connection: 404 page not found

server pod runs on node2, kubectl exec is done on node1 (k8s master)

- Cleanup KubernetesEnv.robot
Some keywords were split in 2 , such as Remove_Client_And_Server_Pod..
into Remove_CLient and Remvoe_Server.., but one node automated tests use
the old keywords. So cleanup to be done after one node tests update.

Signed-off-by: Peter Gubka <pgubka@cisco.com>